### ISSUE TITLE
Works but lacks an UI markup compiler

### ISSUE THREAD

**Issue by pacifio** [Blimster/deact#1]
Would be great if it had an UI compiler
just like JSX is used for writing ui
but what about flutter like UI components like
```dart
Div(
  id: "elementID",
  child:Button(className: 'css_classname', style: Style()),
);
```

would be great

**Comment by Blimster** [comment]
Hi @pacifio,

as I mentioned [here](https://medium.com/@oliver.damm/deact-a-web-ui-framework-for-the-dart-language-73a280e13674?source=friends_link&sk=f0f2653defb96001a310e056909f3752), I do not plan to implement something like JSX in the near future, because it is too much effort for a single developer.

Can you explain your suggestion about Flutter-like UI components? The correct syntax for your suggestion looks like this:
```dart
div(
  id: 'elementID', 
  children: [
    button(
      className: 'css_classname', 
      style: 'some styling')]);
```
The only difference to your suggestion is, that you have to supply the value for the style property as a string and not as a Style object. It is this, what wish to be added?

**Comment by pacifio** [comment]
@Blimster with dart:html library a syntax could look like this
```dart
function home(){
  return div(
  id: 'elementID', 
    children: [
    button(
      className: 'css_classname', 
      style: 'some styling')]);
...
injectToDOM(document.getElementById("root"), home);
}
```

I would love to contribute to this project adding an additional router as well
